.github/workflows/codeql-analysis.yml
CHANGELOG.md
README.md
README.zh-cn.md

Document improvement before release

V0.2.12 rc

---

CHANGELOG.md

this PR is for testing vecel auto deploy.

:memo: Docs: update changelog

---

README.md
README.zh-cn.md

Add a live demo site: [wlanxww's blog](https://wlanxww.com)

📃 Docs: add site: wlanxww's blog

---

CHANGELOG.md
assets/css/_page/_single.scss
assets/css/_partials/_single/_reward.scss
assets/css/_variables.scss
config.toml
i18n/de.toml
i18n/en.toml
i18n/es.toml
i18n/fr.toml
i18n/it.toml
i18n/pl.toml
i18n/pt-BR.toml
i18n/ro.toml
i18n/ru.toml
i18n/sr.toml
i18n/vi.toml
i18n/zh-CN.toml
i18n/zh-TW.toml
layouts/partials/single/reward.html
layouts/posts/single.html

Feat: add feature post reward support

---

README.md
README.zh-cn.md

Add my demo site link.
[My Blog](https://www.nikunokoya.com/)
friends.yml
```
- nickname: Niku
avatar: https://www.nikunokoya.com/images/avatar.jpg
url: https://www.nikunokoya.com/
description: Niku’s blog
```

add demo site: Niku’s blog

---

README.md
README.zh-cn.md

Add my demo site link.
[Wake Huang's Blog](https://www.wakehuang.com)
friends.yml
- nickname: Wake Huang
avatar: https://www.wakehuang.com/images/avatar.png
url: https://www.wakehuang.com
description: Wake Huang's blog

add a FixIt demo site

---

README.md
README.zh-cn.md
assets/data/social.yml
config.toml

:memo: Docs: add douyin social link (#264)

---

CHANGELOG.md
README.md
README.zh-cn.md
assets/css/_core/_breadcrumb.scss
assets/css/_core/_footer.scss
assets/css/_core/_header.scss
assets/css/_core/_layout.scss
assets/css/_core/_media.scss
assets/css/_core/_root.scss
assets/css/_page/_index.scss
assets/css/_page/_single.scss
assets/css/_partials/_single/_code.scss
assets/css/_partials/_single/_comment.scss
assets/css/_partials/_single/_footer.scss
assets/css/_partials/_single/_reward.scss
assets/css/_partials/_single/_toc.scss
assets/css/_partials/_widgets/_fixed-button.scss
assets/css/_partials/_widgets/_github-corner.scss
assets/css/_variables.scss
config.toml
layouts/_default/baseof.html
layouts/partials/breadcrumb.html
layouts/posts/single.html
theme.toml

Required Hugo versions above **0.109.0**

:tada: Feat: add breadcrumb navigation

---

assets/js/theme.js
hugo.toml
layouts/partials/single/comment.html

Add a custom domain setting option for Giscus

:sparkles: Feat: Add a custom domain setting option for Giscus, configured at `params.page.comment.giscus.origin`

---

assets/css/_shortcodes/_index.scss
assets/css/_shortcodes/_timeline.scss
layouts/_default/_markup/render-codeblock-timeline.html

:tada: Feat: add timeline support for code blocks

---

assets/css/_page/_single.scss
assets/css/_partials/_single/_collections.scss
assets/css/_partials/_single/_reward.scss
layouts/partials/custom.html
layouts/partials/single/comment.html
layouts/partials/single/related.html
layouts/posts/single.html

Open block

---

assets/css/_page/_single.scss
layouts/partials/function/content.html
layouts/partials/function/marked-text.html

:tada: Feat: add more type marked text support

---

assets/css/_partials/_widgets/_reading-progress.scss
assets/js/theme.js
layouts/partials/widgets.html

Refactor reading progress

---

i18n/pt-BR.toml

Hi! :wave:
I've been using this .toml for a while for my native language (portuguese) and decided to submit it for code review. 
Hope it helps!

🚧 Fix: add content in pt-BR.toml

---

archetypes/search.md
assets/css/_core/_header.scss
assets/css/_page/_index.scss
assets/css/_page/_special.scss
assets/css/_page/_special/_friends.scss
assets/css/_page/_special/_index.scss
assets/css/_page/_special/_search.scss
assets/js/theme.js
hugo.toml
layouts/page/search.html
layouts/partials/assets.html

:sparkles: Feat: add Google CSE support

---

README.md
README.zh-cn.md
assets/css/_shortcodes/_admonition.scss
hugo.toml
layouts/_default/_markup/render-blockquote-alert.html
theme.toml

https://github.com/gohugoio/hugo/issues/12913
https://github.com/gohugoio/hugo/pull/13122

:bug: Fix: blockquote render hook text parsing (#519)

---

assets/js/theme.js
layouts/partials/plugin/echarts.html
layouts/shortcodes/echarts.html

:sparkles: Feat: add echarts shortcode and code fences support JS object literal

---

hugo.toml
layouts/_default/_markup/render-heading.html
layouts/partials/init/global.html

https://gohugo.io/methods/site/mainsections/

Feat: add `hugo.mainSections` param support

---

assets/js/theme.js
assets/js/util.js
layouts/partials/plugin/echarts.html
layouts/shortcodes/echarts.html

:sparkles: Feat: add `async` and `data` params for echarts shortcode

---

assets/css/_core/_media.scss

Make sure that the scrollbar will not appear in the printed PDF 确保打印出的 PDF 中没有 scrollbar
by ych817

Style: hide scrollbar in print media

---

layouts/partials/head/link.html
layouts/partials/head/meta.html
layouts/partials/home/profile.html
layouts/partials/plugin/icon.html

:bug: Fix: invalid Mastodon configuration and icon function param error

---

assets/css/_partials/_single/_code.scss
assets/css/_partials/_single/_diagram-copy-btn.scss
assets/css/_shortcodes/_mermaid.scss
assets/js/lib/mermaid.js
assets/js/theme.js
hugo.toml
layouts/_partials/assets.html
layouts/_partials/footer.html
layouts/_partials/header.html
layouts/_partials/plugin/echarts.html
layouts/_partials/plugin/mermaid.html
layouts/_partials/single/footer.html

- Add configuration
- securityLevel
- look
- fontFamily
- Fix initialization bug

:sparkles: Feat: enhance Mermaid configuration and fix initialization bug

---

assets/css/_partials/_single/_code.scss
assets/css/_shortcodes/_mermaid.scss
assets/js/lib/mermaid.js
assets/js/theme.js
layouts/_partials/assets.html
layouts/_partials/plugin/mermaid.html

- https://lruihao.cn/posts/mermaid-theming/
- https://github.com/mermaid-js/mermaid/issues/1945#issuecomment-1661264708

:recycle: Refactor: Mermaid theme switching again

---

apps/test/content/posts/script-style-test.md
assets/js/lib/mathjax.js
assets/js/lib/mermaid.js
layouts/_partials/assets.html

FixIt theme assets partial:
- Third-party libraries and plugins
- Theme assets and plugins
- Config script
- MathJax plugin
- Mermaid plugin
- Theme script
- Custom Assets block
- Custom script
Support page level parameters to be passed to `config.js` and `mathjax.js`.

refactor: adjust the loading order and output path of theme resources
